---
env:
  commonjs: true
  es6: true
  node: true
parserOptions:
  ecmaVersion: 2018
  sourceType: module
plugins:
  - prettier
extends:
  - eslint:recommended
  - plugin:prettier/recommended
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
rules:
  prettier/prettier: error
